## Everything in this file gets sourced during `simInit()`,
## and all functions and objects are put into the `simList`.
## To use objects, use `sim$xxx` (they are globally available to all modules).
## Functions can be used without `sim$` as they are namespaced to the module,
## just like functions in R packages.
## If exact location is required, functions will be: `sim$<moduleName>$FunctionName`.
defineModule(sim, list(
  name = "fireWeather",
  description = paste("A module that reads and summarizes weather data to be used for fire modelling. Conceived",
                      "to load and summarize daily weather data generated by BioSIM to be used by LandR Biomass_fireProperties",
                      "and fireSense_dataPrep to calculate fire behaviour indices and model fire frequencies."),
  keywords = c("weather", "climate", "data munging", "BioSIM"),
  authors = person("Ceres", "Barros", email = "cbarros@mail.ubc.ca", role = c("aut", "cre")),
  childModules = character(0),
  version = list(fireWeather = numeric_version("0.0.1"),
                 raster = "3.1-5"),
  spatialExtent = raster::extent(rep(NA_real_, 4)),
  timeframe = as.POSIXlt(c(NA, NA)),
  timeunit = "year",
  citation = list("citation.bib"),
  documentation = list("README.txt", "fireWeather.Rmd"),
  reqdPkgs = list("R.utils", "raster", "data.table", "sf",
                  "cffdrs", "amc", "crayon", "LaF",
                  "PredictiveEcology/SpaDES.core@development",
                  "PredictiveEcology/SpaDES.tools@development",
                  "PredictiveEcology/reproducible@development"),
  parameters = rbind(
    defineParameter("FWIthresh", "integer", 19L, NA, NA,
                    paste("The fire weather index (FWI) minimum threshold value to classify a day as fire-day.",
                          "Defaults to 19, a value commonly used across Canada for fire simulation",
                          "(e.g. Wang et al 2016 Int. J. Wildl. Fire, Podur & Wotton 2011 Int. J. Wildl. Fire)")),
    defineParameter("loadWeatherInChunks", "logical", FALSE, NA, NA,
                    desc = paste("Weather data can be extremely large and require being loaded in chunks. This defaults to FALSE,",
                                 "but if the weatherData file is > 4Gb, will be set to TRUE")),
    defineParameter("MDCmonths", "integer", 7L, 1L, 12L,
                    paste("The months (as a number) across which daily drought code (DC) will be averaged.",
                          "Defaults to July (7)")),
    defineParameter("timePeriod", "numeric", 1960:1990, NA, NA,
                    paste("The time period used for 'weatherDataMCD'. Refers to the period on which the fire frequency",
                          "(i.e. ignition) model - see Marchal et al 2017 - will be fitted.",
                          "Defaults to 1960 to 1990")),
    defineParameter("weatherDataLastYear", "numeric", 1990, NA, NA,
                    "The last calendar year of the weather data. Defaults to 1990"),
    defineParameter("weatherDates", "Date", NULL, NA, NA,
                    paste("OPTIONAL: dates to extract and process weather for in '%Y/%m/%d' format (see as.Date()).",
                    "Overrides 'MDCmonths' and 'timePeriod'. 'weatherDataLastYear' is still necessary to know which",
                    "years in the weather data correspond to calendar years.")),
    defineParameter(".plotInterval", "numeric", 1, NA, NA, "This describes the simulation time interval between plot events"),
    defineParameter(".useCache", "logical", "init", NA, NA,
                    desc = "use caching for the spinup simulation?")
  ),
  inputObjects = bind_rows(
    expectsInput(objectName = "weatherData", objectClass = "sf",
                 desc = paste("Weather and topography point data, to be used to identify fire days.",
                              "Needs to have the following columns: 'month' (optional), 'day' (optional), 'temperature',",
                              "'relativeHumidity', 'windSpeed', 'precipitation'. 'temperature' refers to average air temperature",
                              "in Celsius, 'windSpeed' should be average wind speed (m/s) at 10m height, and 'precipitation' is",
                              "total precipitation in mm. These data can be daily, monthly or yearly averages.",
                              "Defaults to daily weather data between 1691-1990, generated with BioSIM v11 using CA-US climate",
                              "normals 1961-1990 available from BioSIM."),
                 sourceURL = "https://drive.google.com/file/d/1l6GCtYroV8MPyaWxVT92RZW5qMPnnuaU/view?usp=sharing"),
    expectsInput(objectName = "weatherDataCRS", objectClass = "character",
                 desc = paste("The original projection of 'weatherData'. Must be supplied if weatherData is",
                              "supplied by the user or a module. If using default 'weatherData', 'weatherDataCRS'",
                              "defaults to '+proj=longlat +datum=WGS84 +no_defs', the projection used by BioSIM"))
  ),
  outputObjects = bind_rows(
    createsOutput(objectName = "weatherData", objectClass = "sf",
                  desc = paste("Weather point data subset to fire days, according to the FWIthresh parameter.")),
    createsOutput(objectName = "weatherDataMDC", objectClass = "sf",
                  desc = paste("Weather point data  with average drought code (DC) for July, per year,",
                               "calculated using  Canadian Forest Fire Weather Index (FWI) System (see ?cffdrs::fwi)."))
  )
))

## event types
#   - type `init` is required for initialization

doEvent.fireWeather = function(sim, eventTime, eventType) {
  switch(
    eventType,
    init = {
      ### check for more detailed object dependencies:
      ### (use `checkObject` or similar)

      # do stuff for this event
      sim <- Init(sim)

      # schedule future event(s)
      sim <- scheduleEvent(sim, P(sim)$.plotInitialTime, "fireWeather", "plot")
      sim <- scheduleEvent(sim, P(sim)$.saveInitialTime, "fireWeather", "save")
    },
    warning(paste("Undefined event type: \'", current(sim)[1, "eventType", with = FALSE],
                  "\' in module \'", current(sim)[1, "moduleName", with = FALSE], "\'", sep = ""))
  )
  return(invisible(sim))
}

Init <- function(sim) {
  dPath <- asPath(getOption("reproducible.destinationPath", dataPath(sim)), 1)

  ## check that weatherData is in lat/long for fbp calc
  ## Lat/Long (decimal degrees) projection for compatibility with FBP system
  latLong <- "+proj=longlat +datum=WGS84 +no_defs"

  tempRas <- raster(crs = latLong)
  tempRas2 <- raster(crs = sim$weatherDataCRS)
  projectWeatherData <- if (!compareCRS(tempRas, tempRas2)) {
    warning("'weatherDataCRS' is not compatible with cffdrs::fbp. Reprojecting to lat/long, WGS84")
    TRUE
  } else FALSE

  rm(tempRas, tempRas2); .gc()

  ## checks
  if (is.numeric(P(sim)$MDCmonths)) {
    if (max(P(sim)$MDCmonths) > 12 |
        min(P(sim)$MDCmonths) < 1) {
      stop("P(sim)$MDCmonths needs to be [1,12] - one or more values")
    }
  } else {
    stop("P(sim)$MDCmonths should be a numeric vector of month(s)")
  }


  ## does weatherData need to be loaded and processed in chunks?
  ## when using cached .inputObjects, this object disappears so make it again if need be
  if (is.null(mod$loadWeatherInChunks)) {
    mod$loadWeatherInChunks <- P(sim)$loadWeatherInChunks

    if (file.exists(file.path(dPath, "Export (WeatherGeneration).csv"))) {
      mod$loadWeatherInChunks <- file.size(file.path(dPath, "Export (WeatherGeneration).csv")) > 4e+9
    } else {
      message(red("Could not check the size of weatherDataMDC file. Please make sure it's small enough to load into memory"))
    }
  }

  if (!mod$loadWeatherInChunks) {
    if (isTRUE(getOption("LandR.assertions"))) {
      if (any(is.na(sim$weatherData)))
        warning("'weatherData' has missing values - NAs - please check.")

      if (!any(class(sim$weatherData) == "sf"))
        stop(red("'weatherData' has to be a simple features object with points (see ?sf)."))

      colMissing <- setdiff(c("month", "day", "temperature",
                              "relativeHumidity", "windSpeed", "precipitation", "geometry"),
                            names(sim$weatherData))
      if (length(colMissing))
        stop(red(paste("The following columns are missing, or misnamed, in 'weatherData':",
                       paste(colMissing, collapse = ", "))))
    }

    ## reduce weather data to fire days (FWI >= FWIthresh)
    coords <- st_coordinates(sim$weatherData)
    FWIinputs <- data.frame(id = 1:nrow(coords),
                            lat = coords[, "Y"],
                            long = coords[, "X"],
                            yr = sim$weatherData$year,
                            mon = sim$weatherData$month,
                            day = sim$weatherData$day,
                            temp = sim$weatherData$temperature,
                            rh = sim$weatherData$relativeHumidity,
                            ws = sim$weatherData$windSpeed,
                            prec = sim$weatherData$precipitation)

    ## use fwi() defaults to initialise
    FWIinit <- data.frame(ffmc = 85, dmc = 6, dc = 15)

    FWIoutputs <- suppressWarnings({
      fwi(input = FWIinputs,
          init = FWIinit,
          batch = FALSE,
          lat.adjust = TRUE)
    })
    FWIoutputs <- data.table(FWIoutputs)

    ## subset weatherData
    toKeep <- FWIoutputs$FWI >= FWIthresh
    sim$weatherData <- sim$weatherData[toKeep,]

    ## get all monthly drought codes for fireSense
    ## average July DC per year
    sim$weatherDataMDC <- FWIoutputs[, list(meanMDC = mean(DC)), by = .(LAT, LONG, YR)]

  } else {
    ## for some reason the dataLaF is always different
    ## and Cache(process_blocks,...) can't retrieve cached obj, so x (dataLaF) is ignored there
    ## and Caching occurs before to detect changes in the .csv file
    dataModel <- Cache(detect_dm_csv,
                       filename = file.path(dPath, "Export (WeatherGeneration).csv"),
                       header = TRUE,
                       userTags = c("weatherData", "dataModel"),
                       omitArgs = c("userTags"))

    dataLaF <- laf_open(dataModel)

    ## for some reason Cache doesn't seem to retrive cached obj, so we'll try to get it.
    weatherDataCacheIds <- unique(showCache(cachePath(sim), userTags = c("weatherData", "summarized"))$cacheId)
    if (length(weatherDataCacheIds) == 1) {
      message(blue("Loading processed weather data file from cache..."))
      weatherDataList <- loadFromCache(cachePath(sim), weatherDataCacheIds)
    } else {
      message(blue("Reading and processing weather data file in chunks..."))
      weatherDataList <- Cache(process_blocks,
                               x = dataLaF,
                               fun = loadAndProcessWeatherData,
                               projectWeatherData = projectWeatherData,
                               crsProj = latLong,
                               origCrsProj = sim$weatherDataCRS,
                               FWIthresh = P(sim)$FWIthresh,
                               timePeriod = P(sim)$timePeriod,
                               months = P(sim)$MDCmonths,
                             weatherDataLastYear = P(sim)$weatherDataLastYear,
                               progress = FALSE,
                               userTags = c("weatherData", "summarized"),
                               omitArgs = "userTags")
    }

    sim$weatherData <- weatherDataList$weatherData
    sim$weatherDataMDC <- weatherDataList$weatherDataMDC
  }

  ## change column names, convert to sf
  colsKeep <- c("longitude", "latitude", "year", "month", "day", "temperature",
                "relativeHumidity", "windSpeed", "precipitation")
  setnames(sim$weatherData,
           old = c("Longitude", "Latitude", "Year", "Month", "Day", "Air.Temperature",
                   "Relative.Humidity", "Wind.Speed.at.10.meters", "Total.Precipitation"),
           new = colsKeep)
  sim$weatherData <- sim$weatherData[, ..colsKeep]

  setnames(sim$weatherDataMDC, c("LAT", "LONG", "YR"),
           c("latitude", "longitude", "year"))

  sim$weatherData <- st_as_sf(sim$weatherData, coords = c("longitude", "latitude"),
                              crs = latLong, agr = "constant")
  sim$weatherDataMDC <- st_as_sf(sim$weatherDataMDC, coords = c("longitude", "latitude"),
                                 crs = latLong, agr = "constant")

  return(invisible(sim))
}

.inputObjects <- function(sim) {
  cacheTags <- c(currentModule(sim), "function:.inputObjects")
  dPath <- asPath(getOption("reproducible.destinationPath", dataPath(sim)), 1)
  message(currentModule(sim), ": using dataPath '", dPath, "'.")

  if (!suppliedElsewhere("weatherData", sim)) {
    ## get the original CRS
    if (suppliedElsewhere("weatherDataCRS", sim)) {
      warning("'weatherData' does not appear to be supplied to fireWeather,",
              "but 'weatherDataCRS' does. Make sure it corresponds to 'weatherData's CRS projection.")
    } else {
      ## get the shp from BioSIM to obtain projection
      weatherDataPoints <- Cache(prepInputs, targetFile = "1KmGridFoothills.shp",
                                 archive = "1KmGridFoothills.zip",
                                 alsoExtract = "similar",
                                 destinationPath = dPath,
                                 fun = "sf::st_read",
                                 url = "https://drive.google.com/file/d/1XyvWGM0dm1TMiLq4jgYB2vXDjekEQTDl/view?usp=sharing",
                                 userTags = c(cacheTags, "weatherDataPoints"),
                                 omitArgs = "userTags")

      message(blue("Assuming that 'weatherData' CRS projection is ", crs(weatherDataPoints)))
      sim$weatherDataCRS <- crs(weatherDataPoints)
      rm(weatherDataPoints); .gc()
    }

    ## get weather data generated by BioSIM - note that BioSIM saves data in lat/long proj
    mod$loadWeatherInChunks <- P(sim)$loadWeatherInChunks

    if (file.exists(file.path(dPath, "Export (WeatherGeneration).csv"))) {
      mod$loadWeatherInChunks <- file.size(file.path(dPath, "Export (WeatherGeneration).csv")) > 4e+9
    } else {
      message(red("Could not check the size of weatherDataMDC file. Please make sure it's small enough to load into memory"))
    }

    if (!mod$loadWeatherInChunks) {
      sim$weatherData <- Cache(prepInputs,
                               targetFile = "Export (WeatherGeneration).csv",
                               archive = "DailyClimatic_CA-USnormals_1961-1990.zip",
                               fun = "data.table::fread",
                               destinationPath = dPath,
                               url = extractURL("weatherData", sim),
                               overwrite = TRUE,
                               userTags = c(cacheTags, "weatherData"),
                               omitArgs = "userTags")

      ## change column names, convert to sf
      colsKeep <- c("longitude", "latitude", "year", "month", "day", "temperature",
                    "relativeHumidity", "windSpeed", "precipitation")
      setnames(sim$weatherData,
               old = c("Longitude", "Latitude", "Year", "Month", "Day", "Air Temperature",
                       "Relative Humidity", "Wind Speed at 10 meters", "Total Precipitation"),
               new = colsKeep)
      sim$weatherData <- sim$weatherData[, ..colsKeep]
      sim$weatherData <- st_as_sf(sim$weatherData, coords = c("longitude", "latitude"),
                                  crs = sim$weatherDataCRS, agr = "constant")

    } else
      message("weatherData file is too large to load into memory. Will be processed in chunks during init event")
  } else {
    if (!suppliedElsewhere("weatherDataCRS", sim))
      stop(red("'weatherData' appears to be supplied to fireWeather,",
               "but not weatherDataCRS. Please provide 'weatherDataCRS' with the projection of 'weatherData'."))
  }
  return(invisible(sim))
}

### add additional events as needed by copy/pasting from above
