#' Load and process fire data function to be wrapped with LaF::process_blocks
#'
#' This is a function used within LaF::process_blocks to read chunks of a
#' (too large for memory) weather data file, filter them according to fire-days and output a smaller
#' table to be used in the fireWeather module. The function uses cffdr::fwi internally
#' to calculate FWI (with default `init`).
#'
#' @param d the data blocks being generated by LaF::process_blocks
#' @param prevBlock result of the function call that
#' @param projectWeatherData do weather table coordinates need to be projected?
#' @param crsProj if `projectWeatherData` is TRUE, what should be the final projection?
#'  Note that it needs to be compatible with cffdr::fwi
#' @param origCrsProj what is the original projection of the data coordinates?
#' @param FWIthresh what is the threshold (minimum or equal) FWI value to define a weather day?
#' @param timePeriod years to consider for sumamry
#' @param months month(s) across which the daily weather values will be averaged.
#' @param dates a vector of dates in ""%Y/%m/%d" format (see `as.Date`) to filter the weather date by.
#'  If supplied it will override `months` and `timePeriod`. `weatherDataLastYear` is still necessary to
#'  know with years in the weather data correspond to calendar years.
#' @param weatherDataLastYear The last calendar year of the weather data
#' @param averageDC logical. If TRUE, drought code values will be averaged across the `months` of `dates`
#'  selected.
#'
#' @return a summarized version of the original table, subset to fire-day-like weather
#'
#' @seealso \code{cffdr::fwi}
#' @seealso \code{LaF::process_blocks}
#' @export
#' @importFrom cffdrs fwi
#' @importFrom data.table data.table rbind.data.table cbind.data.table
#' @importFrom sf st_as_sf st_coordinates st_transform

loadAndProcessWeatherData <- function(d, prevBlock, projectWeatherData, crsProj,
                                      origCrsProj, FWIthresh, timePeriod, months = 7,
                                      dates = NULL, weatherDataLastYear, averageDC = TRUE) {
  if (!nrow(d))
    return(prevBlock)

  ## make temporary obj
  prevData <- data.table(d)

  ## convert to sf
  prevData <- st_as_sf(prevData, coords = c("Longitude", "Latitude"),
                       crs = origCrsProj, agr = "constant")
  ## project if need be
  if (projectWeatherData)
    prevData <- st_transform(prevData, crs = st_crs(crsProj))

  ## get coordinates and convert back to DT and re-add coordinates
  coords <- st_coordinates(prevData)
  prevData <- data.table(st_drop_geometry(prevData))
  colnames(coords) <- c("Longitude", "Latitude")

  prevData <- cbind(prevData, data.table(coords))

  ## reduce weather data to fire days (FWI >= FWIthresh)
  FWIinputs <- data.frame(id = 1:nrow(prevData),
                          lat = prevData$Latitude,
                          long = prevData$Longitude,
                          yr = prevData$Year,
                          mon = prevData$Month,
                          day = prevData$Day,
                          temp = prevData$Air.Temperature,
                          rh = prevData$Relative.Humidity,
                          ws = prevData$Wind.Speed.at.10.meters,
                          prec = prevData$Total.Precipitation)

  ## use fwi() defaults to initialise
  FWIinit <- data.frame(ffmc = 85, dmc = 6, dc = 15)

  FWIoutputs <- suppressWarnings({
    fwi(input = FWIinputs,
        init = FWIinit,
        batch = FALSE,
        lat.adjust = TRUE)
  })
  FWIoutputs <- data.table(FWIoutputs)

  ## subset weatherData to fire days
  toKeep <- FWIoutputs$FWI >= FWIthresh
  weatherData <- prevData[toKeep,]

  if (!is.null(dates)) {
    browser()
    ## convert weather data dates to calendar dates
    calYears <- FWIoutputs$YR + weatherDataLastYear
    weatherDates <- paste(calYears, FWIoutputs$MON, FWIoutputs$DAY, sep = "/")
    weatherDates <- as.Date(weatherDates)
    toKeep <- weatherDates %in% dates
    FWIoutputs <- FWIoutputs[toKeep]
  } else {
    ## reduce weather data to appropriate time period for MDC
    timePeriod <- timePeriod - weatherDataLastYear
    FWIoutputs <- FWIoutputs[YR %in% timePeriod & MON %in% months]
  }

  if (averageDC) {
    ## average DC across the selected months and days, per year to make weatherDataMDC
    weatherDataMDC <- FWIoutputs[, list(meanMDC = mean(DC)), by = .(LAT, LONG, YR)]
  } else {
    weatherDataMDC <- FWIoutputs[, .(LAT, LONG, YR, MON, DAY, DC)]
  }


  if (is.null(prevBlock)) {
    prevBlock <- list("weatherData" = weatherData, "weatherDataMDC" = weatherDataMDC)
  } else {
    prevBlock$weatherData <- rbind(prevBlock$weatherData, weatherData, use.names = TRUE)
    prevBlock$weatherDataMDC <- rbind(prevBlock$weatherDataMDC, weatherDataMDC, use.names = TRUE)
  }
  return(prevBlock)
}
